# Generated by Django 3.2.6 on 2021-08-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_area', models.CharField(choices=[('HU', 'Human'), ('SO', 'Social'), ('NA', 'Natural'), ('FO', 'Formal'), ('AP', 'Applied')], max_length=2)),
                ('subject_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
