# Generated by Django 3.2.6 on 2021-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='display_name',
            new_name='friendly_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='science_area',
            new_name='science',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article', models.FileField(upload_to='uploads/')),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subjects', models.ManyToManyField(to='articles.Subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
