# Generated by Django 3.2.7 on 2021-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210910_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='proposal',
            field=models.BooleanField(default=False),
        ),
    ]
