# Generated by Django 3.2.7 on 2021-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpeg', upload_to=''),
        ),
    ]
