# Generated by Django 3.2.7 on 2021-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_stakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='/media/noimage.jpeg', upload_to=''),
        ),
    ]
