# Generated by Django 3.2.6 on 2021-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0006_auto_20210825_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('level', models.DecimalField(blank=True, decimal_places=1, max_digits=4)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('subscribers', models.DecimalField(blank=True, decimal_places=0, max_digits=9)),
                ('following', models.ManyToManyField(blank=True, to='academics.Academic')),
                ('subjects', models.ManyToManyField(to='articles.Subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
