# Generated by Django 3.2.7 on 2021-09-07 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_remove_academic_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_county',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_street_address1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_street_address2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='academic',
            name='default_town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='academic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
