# Generated by Django 3.2.7 on 2021-09-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_academic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='subscribers',
        ),
    ]
