# Generated by Django 3.2.7 on 2021-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_academic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='image',
            field=models.ImageField(blank=True, default='https://the-home-of-learning.s3.eu-west-2.amazonaws.com/media/noimage.jpeg', upload_to=''),
        ),
    ]
